Trailing ; on FUNCTIONAL_DECLARE()s followed by additional declarations causes errors when compiling on windows.
..\pecl\functional-php\functional.c(939) : error C2143: syntax error : missing ';' before 'type'
..\pecl\functional-php\functional.c(956) : error C2065: 'drop' : undeclared identifier
..\pecl\functional-php\functional.c(959) : error C2065: 'drop' : undeclared identifier
..\pecl\functional-php\functional.c(974) : error C2065: 'drop' : undeclared identifier
..\pecl\functional-php\functional.c(977) : error C2065: 'drop' : undeclared identifier

etc.